// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@2.2.0";

// src/lib/mcp/tools/list-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/posts.ts
var SITE = "https://iamrusiru.lovable.app";
async function fetchPosts(signal) {
  const res = await fetch(`${SITE}/posts.json`, {
    signal,
    headers: { accept: "application/json" }
  });
  if (!res.ok) {
    throw new Error(`Could not load posts (${res.status} from ${SITE}/posts.json)`);
  }
  const data = await res.json();
  return Array.isArray(data) ? data : [];
}
function postSummary(post) {
  return {
    title: post.title,
    slug: post.slug,
    url: post.url,
    date: post.date,
    category: post.category,
    readTime: post.readTime,
    excerpt: post.excerpt,
    tags: post.tags
  };
}

// src/lib/mcp/tools/list-posts.ts
var list_posts_default = defineTool({
  name: "list_posts",
  title: "List blog posts",
  description: "List published posts on Rusiru Rathmina's blog, newest first. Optionally filter by category or tag.",
  inputSchema: {
    category: z.string().trim().optional().describe("Filter by category, case-insensitive."),
    tag: z.string().trim().optional().describe("Filter by tag, case-insensitive."),
    limit: z.number().int().min(1).max(50).optional().describe("Max posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, tag, limit }, ctx) => {
    const posts = await fetchPosts(ctx.signal);
    const cat = category?.toLowerCase();
    const tg = tag?.toLowerCase();
    const filtered = posts.filter((p) => {
      if (cat && p.category.toLowerCase() !== cat) return false;
      if (tg && !p.tags.some((t) => t.toLowerCase() === tg)) return false;
      return true;
    });
    const items = filtered.slice(0, limit ?? 20).map(postSummary);
    return {
      content: [
        {
          type: "text",
          text: items.length === 0 ? "No posts matched those filters." : items.map((p) => `- ${p.title} (${p.category}, ${p.date})
  ${p.url}
  ${p.excerpt}`).join("\n")
        }
      ],
      structuredContent: { total: filtered.length, posts: items }
    };
  }
});

// src/lib/mcp/tools/search-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z as z2 } from "npm:zod@^4.6.5";
var search_posts_default = defineTool2({
  name: "search_posts",
  title: "Search blog posts",
  description: "Full-text search across titles, excerpts, tags, keywords and body content of the blog's published posts.",
  inputSchema: {
    query: z2.string().trim().min(2).describe("Search phrase, for example 'sql injection'."),
    limit: z2.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const posts = await fetchPosts(ctx.signal);
    const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
    const scored = posts.map((p) => {
      const title = p.title.toLowerCase();
      const meta = [p.excerpt, p.category, ...p.tags, ...p.seoKeywords ?? []].join(" ").toLowerCase();
      const body = p.body.toLowerCase();
      let score = 0;
      for (const t of terms) {
        if (title.includes(t)) score += 6;
        if (meta.includes(t)) score += 3;
        if (body.includes(t)) score += 1;
      }
      return { post: p, score };
    }).filter((r) => r.score > 0).sort((a, b) => b.score - a.score).slice(0, limit ?? 10);
    const results = scored.map((r) => ({ ...postSummary(r.post), score: r.score }));
    return {
      content: [
        {
          type: "text",
          text: results.length === 0 ? `No posts matched "${query}".` : results.map((p) => `- ${p.title}
  ${p.url}
  ${p.excerpt}`).join("\n")
        }
      ],
      structuredContent: { query, results }
    };
  }
});

// src/lib/mcp/tools/get-post.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z as z3 } from "npm:zod@^4.6.5";
var get_post_default = defineTool3({
  name: "get_post",
  title: "Get a blog post",
  description: "Fetch the full text of one published blog post by its slug, including tags, FAQ entries and related posts.",
  inputSchema: {
    slug: z3.string().trim().min(1).describe("Post slug, for example 'git-workflow-tips'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const posts = await fetchPosts(ctx.signal);
    const post = posts.find((p) => p.slug.toLowerCase() === slug.toLowerCase());
    if (!post) {
      throw new ToolError(
        `No post found with slug "${slug}". Use list_posts or search_posts to find valid slugs.`
      );
    }
    const faqText = post.faq?.length ? `

## FAQ
${post.faq.map((f) => `**${f.question}**
${f.answer}`).join("\n\n")}` : "";
    return {
      content: [
        {
          type: "text",
          text: `# ${post.title}

${post.date} \xB7 ${post.category} \xB7 ${post.url}

${post.body}${faqText}`
        }
      ],
      structuredContent: JSON.parse(JSON.stringify({ post }))
    };
  }
});

// src/lib/mcp/tools/list-topics.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.2.0";
var list_topics_default = defineTool4({
  name: "list_topics",
  title: "List categories and tags",
  description: "List every category and tag used on the blog, with how many posts use each. Useful before filtering list_posts.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    const posts = await fetchPosts(ctx.signal);
    const count = (values) => {
      const map = /* @__PURE__ */ new Map();
      for (const v of values) map.set(v, (map.get(v) ?? 0) + 1);
      return [...map.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([name, posts2]) => ({ name, posts: posts2 }));
    };
    const categories = count(posts.map((p) => p.category));
    const tags = count(posts.flatMap((p) => p.tags));
    return {
      content: [
        {
          type: "text",
          text: [
            `Categories: ${categories.map((c) => `${c.name} (${c.posts})`).join(", ")}`,
            `Tags: ${tags.map((t) => `${t.name} (${t.posts})`).join(", ")}`
          ].join("\n\n")
        }
      ],
      structuredContent: { totalPosts: posts.length, categories, tags }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "i-am-rusiru",
  title: "I am Rusiru",
  version: "0.1.0",
  instructions: "Read-only access to iamrusiru, the engineering blog of Rusiru Rathmina, covering code, security (OWASP), career lessons and side projects. Use `search_posts` to find articles by topic, `list_posts` to browse newest first or filter by category/tag, `list_topics` to see available categories and tags, and `get_post` to read one article in full. All content is public.",
  tools: [search_posts_default, list_posts_default, get_post_default, list_topics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.2.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
